---
apiVersion: v1
kind: Namespace
metadata:
  name: helloworld
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  namespace: helloworld
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: alexandreroman/helloworld
        ports:
        - containerPort: 9000
        env:
        - name: MESSAGE
          value: "Bonjour le monde !"
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-lb
  labels:
    app: helloworld
  namespace: helloworld
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    app: helloworld
