---
apiVersion: v1
kind: Namespace
metadata:
  name: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - helloworld
            topologyKey: kubernetes.io/hostname
      containers:
      - name: helloworld
        image: alexandreroman/helloworld
        ports:
        - containerPort: 9000
        env:
        - name: MESSAGE
          value: "Bonjour le monde !"
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-lb
  labels:
    app: helloworld
  namespace: helloworld
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    app: helloworld
